// aski-core — rkyv contract types for askic↔veric↔semac.
//
// Parse tree domains generated by corec from core/*.core.
// Name wrappers, Span, and Primitive defined here.
//
// Regenerate: corec core generated/aski.rs

use rkyv::{Archive, Serialize, Deserialize};

// ── Typed name wrappers ──────────────────────────────────
// Each wraps a String. In true sema these become domain
// variant indices with no strings. For the bootstrap: String.

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct VariantName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct FieldName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct MethodName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct TraitName(pub String);

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeParamName(pub String);

// ── Source position ──────────────────────────────────────

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Span {
    pub start: u32,
    pub end: u32,
}

// ── Built-in primitives ─────────────────────────────────
// Types that exist without being declared in any module.
// The Primitive struct is generated by corec from core/primitive.aski.

impl Primitive {
    pub fn all() -> Vec<Primitive> {
        [
            ("U8", 0), ("U16", 0), ("U32", 0), ("U64", 0),
            ("I8", 0), ("I16", 0), ("I32", 0), ("I64", 0),
            ("F32", 0), ("F64", 0),
            ("Bool", 0), ("String", 0), ("Char", 0),
            ("Vec", 1), ("Option", 1), ("Box", 1),
            ("Result", 2),
        ].iter().map(|(n, a)| Primitive {
            name: n.to_string(), arity: *a,
        }).collect()
    }

    pub fn is_primitive(name: &str) -> bool {
        Self::all().iter().any(|p| p.name == name)
    }

    pub fn arity_of(name: &str) -> Option<u32> {
        Self::all().iter().find(|p| p.name == name).map(|p| p.arity)
    }
}

// ── Generated parse tree domains ─────────────────────────

include!("../generated/aski.rs");
