// aski-core — the rkyv contract types for askic↔veric↔semac.
//
// Parse tree entities generated by corec from core/*.core.
// Typed Name newtypes (one per LabelKind that names an entity)
// and LiteralValue hand-written here; entities generated.
//
// Regenerate: corec core generated/aski.rs

use rkyv::{Archive, Serialize, Deserialize};

// ─────────────────────────────────────────────────────────────
// Typed Name newtypes — one per naming role.
//
// Each is a tuple newtype over String. Different kinds cannot
// be substituted for one another; a StructName is not a
// FieldName, even if both wrap the same string.
//
// Post-resolution (veri-core), these become absolute references
// to entities; at aski-core level they carry the source name.
// ─────────────────────────────────────────────────────────────

macro_rules! name_newtype {
    ($name:ident) => {
        #[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
        pub struct $name(pub String);
    };
}

// Module-level entity names
name_newtype!(ModuleName);
name_newtype!(EnumName);
name_newtype!(StructName);
name_newtype!(NewtypeName);
name_newtype!(ConstName);
name_newtype!(FfiName);
name_newtype!(TraitName);

// Sub-entity names
name_newtype!(VariantName);
name_newtype!(FieldName);
name_newtype!(MethodName);
name_newtype!(SigName);

// Local / body names
name_newtype!(InstanceName);
name_newtype!(ParamName);
name_newtype!(BindingName);
name_newtype!(RoleName);
name_newtype!(ItemName);

// Origin places
name_newtype!(PlaceName);

// Generic type references
// TypeName covers any type-in-position reference (could be enum, struct,
// newtype, trait, primitive — veri-core resolves the kind).
name_newtype!(TypeName);

// Generic parameter (introduced by $X in source)
name_newtype!(GenericName);

// ─────────────────────────────────────────────────────────────
// Literal values (for Const and Pattern)
// ─────────────────────────────────────────────────────────────

#[derive(Archive, Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum LiteralValue {
    Int(i64),
    Float(f64),
    Str(String),
    Bool(bool),
    Char(u32),
    Unit,
}

// ─────────────────────────────────────────────────────────────
// Built-in primitives — types that exist without module declaration
// ─────────────────────────────────────────────────────────────

impl Primitive {
    pub fn all() -> Vec<Primitive> {
        [
            ("U8", 0), ("U16", 0), ("U32", 0), ("U64", 0),
            ("I8", 0), ("I16", 0), ("I32", 0), ("I64", 0),
            ("F32", 0), ("F64", 0),
            ("Bool", 0), ("String", 0), ("Char", 0),
            ("Vec", 1), ("Option", 1), ("Box", 1),
            ("Result", 2),
        ]
        .iter()
        .map(|(n, a)| Primitive {
            name: n.to_string(),
            arity: *a,
        })
        .collect()
    }

    pub fn is_primitive(name: &str) -> bool {
        Self::all().iter().any(|p| p.name == name)
    }

    pub fn arity_of(name: &str) -> Option<u32> {
        Self::all().iter().find(|p| p.name == name).map(|p| p.arity)
    }
}

// ─────────────────────────────────────────────────────────────
// Generated parse tree entities
// ─────────────────────────────────────────────────────────────

include!("../generated/aski.rs");
